version: "3"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    networks:
      - api-network

networks:
  api-network:
    driver: bridge